### ISSUE TITLE
Add instruction to manually `npm i` functions dir

### ISSUE THREAD

**Issue by TheNando** [mpigsley/keyforge-arena#12]
I'm not sure if I only had this problem because of using Yarn instead of NPM, but I had to manually run `npm i` within the functions dir in order to get the `deploy:functions` script to run correctly.

**Comment by mpigsley** [comment]
Ahhh, yes yes. I'll update the command. Thank you!

**Comment by mpigsley** [comment]
@TheNando looks like there are already instructions in the README to install in the functions directory already.
